In [10]:
import numpy as np
import tensorflow as tf

In [11]:
celsius = np.array([-40, -25, -10, 0, 10, 25, 35, 50], dtype = float)
farenheit = np.array([-40, -13, 14, 32, 50, 77, 95, 122], dtype = float)

In [12]:
capa1 = tf.keras.layers.Dense(units = 3, input_shape = [1])
capa2 = tf.keras.layers.Dense(units = 3)
salida = tf.keras.layers.Dense(units=1)
modelo = tf.keras.Sequential([capa1,capa2,salida])

In [13]:
modelo.compile(
    optimizer = tf.keras.optimizers.Adam(0.1),
    loss = "mean_squared_error"
)

In [14]:
print("A punto de entrenar al modelo:")
historia = modelo.fit(celsius, farenheit, epochs = 1000)
print("Modelo ya entrenado...")

A punto de entrenar al modelo:
Epoch 1/1000
1/1 [==============================] - 1s 624ms/step - loss: 1020.2292
Epoch 2/1000
1/1 [==============================] - 0s 10ms/step - loss: 1394.4430
Epoch 3/1000
1/1 [==============================] - 0s 10ms/step - loss: 1016.7020
Epoch 4/1000
1/1 [==============================] - 0s 10ms/step - loss: 923.3617
Epoch 5/1000
1/1 [==============================] - 0s 10ms/step - loss: 1064.3202
Epoch 6/1000
1/1 [==============================] - 0s 9ms/step - loss: 874.4247
Epoch 7/1000
1/1 [==============================] - 0s 8ms/step - loss: 765.2411
Epoch 8/1000
1/1 [==============================] - 0s 9ms/step - loss: 801.2785
Epoch 9/1000
1/1 [==============================] - 0s 9ms/step - loss: 815.8502
Epoch 10/1000
1/1 [==============================] - 0s 9ms/step - loss: 747.3828
Epoch 11/1000
1/1 [==============================] - 0s 10ms/step - loss: 646.2259
Epoch 12/1000
1/1 [==============================] - 0s 9ms/step 

In [17]:
resultado = modelo.predict([-33,10,29])
print(resultado)

1/1 [==============================] - 0s 38ms/step
[[-27.337229]
 [ 49.982998]
 [ 84.14775 ]]


In [18]:
modelo.get_weights()

[array([[-0.00979472, -0.25375253, -0.5382247 ]], dtype=float32),
 array([-3.0916905, -3.205751 , -3.2294567], dtype=float32),
 array([[ 0.32352215,  0.8357022 , -0.04831008],
        [ 0.50591034,  0.871315  , -0.25254318],
        [ 0.29703292,  0.9140351 , -1.0505705 ]], dtype=float32),
 array([-3.1985683, -3.2608168,  3.2157893], dtype=float32),
 array([[-1.4306002],
        [-0.8674638],
        [ 1.1993599]], dtype=float32),
 array([3.1725242], dtype=float32)]